# Generated by Django 5.0.1 on 2024-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='title',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
