# Generated by Django 5.0.1 on 2024-02-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_userrole_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('CUSTOMER', 'CUSTOMER'), ('EMPLOYEE_OWNER', 'EMPLOYEE_OWNER'), ('CUSTOMER_OWNER', 'CUSTOMER_OWNER')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
