# Generated by Django 5.0.1 on 2024-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorageitem',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('TEMPLATE', 'TEMPLATE'), ('REPORT', 'REPORT')], default='IMAGE', max_length=20),
        ),
    ]
