# Generated by Django 5.0.1 on 2024-03-26 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0003_alter_facility_description_alter_facility_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('IN_PROCESS', 'IN_PROCESS'), ('DONE', 'DONE')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections_as_inspector', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections_as_pilot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
