# Generated by Django 5.0.1 on 2024-04-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_storage_items', '0003_template'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('MAJOR', 'MAJOR'), ('MINOR', 'MINOR'), ('TRIVIAL', 'TRIVIAL')], max_length=10)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('file_storage_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file_storage_items.filestorageitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspection')),
            ],
        ),
    ]
