# Generated by Django 5.0.1 on 2024-02-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('Aircraft', 'Aircraft'), ('Airport', 'Airport'), ('Bridges', 'Bridges'), ('Buildings', 'Buildings'), ('Commercial Buildings', 'Commercial_Buildings'), ('Construction', 'Construction'), ('Cranes', 'Cranes'), ('Dam', 'Dam'), ('Drilling Heads', 'Drilling_Heads'), ('Electrical Pylons', 'Electrical_Pylons'), ('Factories', 'Factories'), ('Mining Site', 'Mining_Site'), ('Motorways', 'Motorways'), ('Nuclear', 'Nuclear'), ('Other', 'Other'), ('Pipeline', 'Pipeline'), ('Power Station', 'Power_Station'), ('Railway', 'Railway'), ('Refineries', 'Refineries'), ('Solar Farms & Panels', 'Solar_Farms_Panels'), ('Stockpile', 'Stockpile'), ('Storage Tanks', 'Storage_Tanks'), ('Substation', 'Substation'), ('Telecom Tower & Mobile Cell Sites', 'Telecom_Tower_Mobile_Cell_Sites'), ('Tunnels', 'Tunnels'), ('Wind Turbines', 'Wind_Turbines')], max_length=50),
        ),
    ]
