# Generated by Django 5.0.1 on 2024-02-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
