# Generated by Django 5.0.1 on 2024-02-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('phone', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=300, null=True)),
                ('company_type', models.CharField(choices=[('INSPECTING', 'INSPECTING'), ('INSPECTED', 'INSPECTED')], max_length=15)),
                ('inspecting_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
        ),
    ]
